Apricot-S/majsoulrpa

src/majsoulrpa/presentation/home.py

* fix: inputs that do not exactly match will result in an error
* refactor: move the generation of templates that are only used within the try statement to within the try statement

Fix/join room fullmatch (#74)

---

examples/join_room.py
examples/login_imap.py
examples/moqie.py
examples/moqie_3player.py
examples/skip_after_lizhi.py
pyproject.toml
src/majsoulrpa/__init__.py
src/majsoulrpa/_impl/browser.py
src/majsoulrpa/_impl/template.py
src/majsoulrpa/_impl/zmq_client.py
src/majsoulrpa/_mitmproxy/sniffer.py
src/majsoulrpa/_rpa.py
src/majsoulrpa/common/__init__.py
src/majsoulrpa/config/__init__.py
src/majsoulrpa/presentation/__init__.py
src/majsoulrpa/presentation/_presentation_creator.py
src/majsoulrpa/presentation/home.py
src/majsoulrpa/presentation/match/__init__.py
src/majsoulrpa/presentation/match/event/__init__.py
src/majsoulrpa/presentation/match/match.py
src/majsoulrpa/presentation/match/state.py
src/majsoulrpa/presentation/room/__init__.py
src/majsoulrpa/presentation/room/base.py
src/majsoulrpa/presentation/room/guest.py
src/majsoulrpa/presentation/room/host.py
src/majsoulrpa/remote_browser/__init__.py
src/majsoulrpa/remote_browser/_remote_browser.py
src/majsoulrpa/yostar_login/__init__.py

* style: add ignore rules
* style: remove unnecessary noqa #66
* style: remove noqa of PLR09**
* refactor: add __all__ instead of noqa F401 #66

Style/66 add ignore ruff rules (#78)

---

src/majsoulrpa/config/schema.json

feat: change authentication in config to optional #64

---

src/majsoulrpa/presentation/match/state.py

* fix: change to pop from the shoupai only when it matches the fulu tiles
* fix: correct the indentation hierarchy

Fix/match state bug (#82)

---

src/majsoulrpa/presentation/match/match.py

* refactor: change the exception type and add a message
* refactor: assign the number of combinations to a variable

Refactor/screenshots of rare situations during the match (#97)

---

src/majsoulrpa/presentation/home.py

* fix: change the order of API reading and notifications closing
* refactor: move the processing when an inconsistent message arrives to a case
* refactor: separate the process of receiving daily bonuses
* docs: add notes regarding events that are outside the scope of support

Refactor/home month ticket (#112)

---

pyproject.toml
src/majsoulrpa/_rpa.py

関数・クラス・メソッドに対する docstring を書き始めたので first try として PR を出します． docstring のスタイルはとりあえず Google のもの (https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) を採用していますが，他のスタイルが良いなどあればコメントお願いします．

docs: add docstrings for `RPA`

---

pyproject.toml
src/majsoulrpa/_rpa.py

* docs: add docstrings for `RPA`
* docs: add setting for docstrings in ruff
* docs: fix and add settings for docstrings in ruff
* docs: remove type annotations from docstrings
* docs: clarify document
* docs: clarify document

docs: add docstrings for `RPA` (#111)

---

src/majsoulrpa/__init__.py

* add a docstring to `majsoulrpa`

docs: add a docstring to `majsoulrpa`

---

src/majsoulrpa/presentation/__init__.py

* add a docstring to the `majsoulrpa.presentation` package

docs: add a docstring to `majsoulrpa.presentation`

---

src/majsoulrpa/presentation/login.py

* add docstrings to the `majsoulrpa.presentation.login` module

docs: add docstrings to `majsoulrpa.presentation.login`

---

src/majsoulrpa/presentation/auth.py

* add docstrings to the `majsoulrpa.presentation.auth` module

docs: add docstrings to `majsoulrpa.presentation.auth`

---

src/majsoulrpa/presentation/home.py

* add docstrings to the `majsoulrpa.presentation.home` module

docs: add docstrings to `majsoulrpa.presentation.home`

---

src/majsoulrpa/presentation/room/guest.py

* add docstrings to the `majsoulrpa.presentation.room.guest` module

docs: add docstrings to `majsoulrpa.presentation.room.guest`

---

src/majsoulrpa/yostar_login/__init__.py
src/majsoulrpa/yostar_login/_yostar_login.py

* add docstrings to the modules in the `majsoulrpa.yostar_login` package

docs: add docstrings to `majsoulrpa.yostar_login`

---

src/majsoulrpa/presentation/room/base.py

* add docstrings to the `majsoulrpa.presentation.room.base` module

docs: add docstrings to `majsoulrpa.presentation.room.base`

---

src/majsoulrpa/presentation/room/host.py

* add docstrings to the `majsoulrpa.presentation.room.host` module

docs: add docstrings to `majsoulrpa.presentation.room.host`

---

src/majsoulrpa/presentation/match/match.py

fix: add processing when DaminGang is obstructed by Rong. #21 (#148)

---

examples/join_room.py
src/majsoulrpa/presentation/__init__.py
src/majsoulrpa/presentation/home.py
src/majsoulrpa/presentation/room/guest.py

* feat: return the reason for failure to join the room
* docs: update example
* fix: discard messages when the time between logging in and entering the room was fast.
* refactor: move the exception inside the case

Feat/#118 return failure reason of join room (#152)

---

src/majsoulrpa/presentation/match/match.py

* fix: fix click position of no melding
* fix: fix click position of hu
* fix: change rounding to truncation
* fix: modify click range
* fix: add delay to combination selection

Fix/correct the click position deviation (#161)

---

src/majsoulrpa/_impl/browser.py
src/majsoulrpa/presentation/match/match.py
src/majsoulrpa/remote_browser/_remote_browser.py

* fix: add mouse movement function
* fix: increase maximum latency
* fix: prevent mouse from remaining on tiles in the hand
* fix: deal with slow tile sorting

Fix/move mouse (#163)

---

poetry.lock
pyproject.toml

* chore: update dependencies
* chore: update Ruff settings
* chore: remove unnecessary packages

Chore/update dependencies (#167)

---

pyproject.toml
src/majsoulrpa/presentation/match/event/no_tile.py
src/majsoulrpa/presentation/room/guest.py
src/majsoulrpa/presentation/room/host.py

* chore: add rules to ignore
* docs: remove unused noqa directive
* docs: add TODO contents

Chore/ignore ruff todo (#171)

---

src/majsoulrpa/config/_config.py

* refactor: Defer validator construction until the first `get_config` call.
* refactor: tweak

Refactor/cache validator (#225)

---

README.md
src/majsoulrpa/remote_browser/_remote_browser.py

* feat: add user_data_dir
* style: Adjust blank lines
* feat: Add branch using user_data
* refactor: Consolidate input waiting in one place
* feat: Modify the message waiting for input.
* docs: update announcements

Feat/remote browser user data (#232)

---

src/majsoulrpa/presentation/home.py
src/majsoulrpa/presentation/match/match.py

* fix: support for ".lq.Lobby.fetchVoteActivity"
* fix: support for ".lq.Lobby.fetchVoteActivity"

Fix/fetchVoteActivity (#243)

---

src/majsoulrpa/_impl/browser.py

fix: Avoid creating a extra page #121

---

src/majsoulrpa/_impl/browser.py

fix: Avoid creating a extra page #121 (#250)

---

.gitignore
pyproject.toml

chore: Migrate from poetry to rye

---

pyproject.toml

PyPI 分類子を追加する
- Python 3.12 を追加
- 誤って PyPI にアップロードされないように "Private :: Do Not Upload" を追加

chore: Add classifiers

---

README.md

インストール方法を変更する
- poetry から rye に移行したので、`poetry install` から `pip install` に変更する
- 動作に必要な playwright のインストールを追加する

docs: Change the installation method

---

README.md

chore: delete old announcements

---

src/majsoulrpa/presentation/room/host.py

fix: Change the image to wait for #273

---

pyproject.toml

chore: Update dependencies

---

pyproject.toml

docs: Write the names of the lint rule to ignore

---

pyproject.toml

chore: Update dev-dependencies

---

pyproject.toml

chore: Exclude files generated by protoc from mypy inspection

---

README.md

docs: Remove unnecessary copyright notice in `README.md`

---

.gitignore
pyproject.toml

chore: Specify development dependencies in a PEP 735 compliant way
